[package]
name = "jeria/helmetgame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5.1"
Janitor = "howmanysmall/janitor@^1.15.5"